version: '2'
services:
  
  population-complaints-api:
    build:
      context: .
    depends_on:
      - postgres
    volumes:
      - "./src:."
    ports:
      - "3333:3333"
    command: yarn start

  postgres:
    image: postgres:latest
    volumes:
      - ./data/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password1!
      POSTGRES_DB: consumers