version: '2'
services:
  
  api:
    build: .
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - "3333:3333"
    command: ["./wait-for-postgres.sh", "postgres", "5432", "yarn start"]

  postgres:
    image: postgres:latest
    volumes:
      - ./data/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Password1!
      POSTGRES_DB: consumers